/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.DBillsDetails;
import Logic.LBillsDetails;
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author FeedzOne
 */
public class FrmDetalleVentas extends javax.swing.JDialog {

    DefaultTableModel myModel;

    /**
     * Creates new form FrmDetalleFacturas
     */
    public FrmDetalleVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        IDField.setEditable(false);
        LineField.setEditable(false);
        SupplierField.setEditable(false);
        DateField.setEditable(false);
        TotalField.setEditable(false);
        myModel = (DefaultTableModel) tblSales.getModel();

        tblSales.getColumn("CODE").setWidth(15);
        tblSales.getColumn("CODE").setPreferredWidth(15);

        tblSales.getColumn("DESCRIPTION").setWidth(200);
        tblSales.getColumn("DESCRIPTION").setPreferredWidth(200);

        tblSales.getColumn("QUANTITY").setWidth(20);
        tblSales.getColumn("QUANTITY").setPreferredWidth(20);

        tblSales.getColumn("PRICE/UNIT").setWidth(20);
        tblSales.getColumn("PRICE/UNIT").setPreferredWidth(20);

        tblSales.getColumn("UNIT").setWidth(20);
        tblSales.getColumn("UNIT").setPreferredWidth(20);

        //tblSales.getColumn("LINE").setWidth(20);
        //tblSales.getColumn("LINE").setPreferredWidth(20);
        tblSales.getColumn("TOTAL").setWidth(20);
        tblSales.getColumn("TOTAL").setPreferredWidth(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SupplierField = new javax.swing.JTextField();
        LineField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        TotalField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        GenerateBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BILLS DETAILS");
        setBackground(new java.awt.Color(24, 242, 7));

        jPanel1.setBackground(new java.awt.Color(31, 31, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setBackground(new java.awt.Color(24, 24, 27));
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("ID:");

        jLabel2.setBackground(new java.awt.Color(24, 24, 27));
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Line:");

        jLabel3.setBackground(new java.awt.Color(24, 24, 27));
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Supplier:");

        jLabel4.setBackground(new java.awt.Color(24, 24, 27));
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Date:");

        SupplierField.setBackground(new java.awt.Color(80, 80, 80));
        SupplierField.setForeground(new java.awt.Color(238, 238, 238));

        LineField.setBackground(new java.awt.Color(80, 80, 80));
        LineField.setForeground(new java.awt.Color(238, 238, 238));

        IDField.setBackground(new java.awt.Color(50, 50, 50));
        IDField.setForeground(new java.awt.Color(238, 238, 238));

        tblSales.setBackground(new java.awt.Color(80, 80, 80));
        tblSales.setForeground(new java.awt.Color(238, 238, 238));
        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "DESCRIPTION", "QUANTITY", "UNIT", "PRICE/UNIT", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblSales);

        TotalField.setBackground(new java.awt.Color(80, 80, 80));
        TotalField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TotalField.setForeground(new java.awt.Color(238, 238, 238));
        TotalField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("TOTAL:");

        DateField.setBackground(new java.awt.Color(80, 80, 80));
        DateField.setForeground(new java.awt.Color(238, 238, 238));

        GenerateBTN1.setBackground(new java.awt.Color(24, 24, 27));
        GenerateBTN1.setForeground(new java.awt.Color(238, 238, 238));
        GenerateBTN1.setText("Generate Report");
        GenerateBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GenerateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LineField)
                    .addComponent(SupplierField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SupplierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(GenerateBTN1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBTN1ActionPerformed
        // TODO add your handling code here:
        JFileChooser selection = new JFileChooser();
        int op = selection.showSaveDialog(null);
        if (op == JFileChooser.APPROVE_OPTION) {
            String route = selection.getSelectedFile().getAbsolutePath();
            String name = route + IDField.getText() + ".xlsx";
            String reportname = "ReceiptsDetails";
            XSSFWorkbook inventorybook = new XSSFWorkbook();
            XSSFSheet inventoryleaf = inventorybook.createSheet(reportname);

            String[] titles = new String[]{"CODE", "DESCRIPTION", "QUANTITY", "UNIT", "PRICE/UNIT", "TOTAL"};

            Font titlesfont = inventorybook.createFont();
            titlesfont.setBold(true);

            XSSFRow ID = inventoryleaf.createRow(1);
            XSSFCell cellsale1 = ID.createCell(0);
            XSSFCell cellsale2 = ID.createCell(1);
            cellsale1.setCellValue("# SALE: ");
            cellsale2.setCellValue(IDField.getText());
            
            XSSFRow Line = inventoryleaf.createRow(3);
            XSSFCell cellline1 = ID.createCell(0);
            XSSFCell cellline2 = ID.createCell(1);
            cellline1.setCellValue("LINE: ");
            cellline2.setCellValue(LineField.getText());
            
            XSSFRow Supplier = inventoryleaf.createRow(5);
            XSSFCell cellsupplier1 = ID.createCell(0);
            XSSFCell cellsupplier2 = ID.createCell(1);
            cellsupplier1.setCellValue("SUPPLIER: ");
            cellsupplier2.setCellValue(SupplierField.getText());
            
            XSSFRow Date = inventoryleaf.createRow(7);
            XSSFCell celldate1 = ID.createCell(0);
            XSSFCell celldate2 = ID.createCell(1);
            celldate1.setCellValue("DATE: ");
            celldate2.setCellValue(DateField.getText());
            
            XSSFRow title = inventoryleaf.createRow(10);
            for (int i = 0; i < titles.length; i++) {
                XSSFCell cell = title.createCell(i);
                cell.setCellValue(titles[i]);
            }
            int inventoryRow = 11;
            for (int i = 0; i < tblSales.getRowCount(); i++) {
                XSSFRow content = inventoryleaf.createRow(inventoryRow);
                inventoryRow++;
                for (int j = 0; j < tblSales.getColumnCount(); j++) {
                    XSSFCell cell = content.createCell(j);
                    cell.setCellValue(tblSales.getValueAt(i, j).toString());
                }
            }
            inventoryleaf.autoSizeColumn(0);
            inventoryleaf.autoSizeColumn(1);
            inventoryleaf.autoSizeColumn(2);
            inventoryleaf.autoSizeColumn(3);
            inventoryleaf.autoSizeColumn(4);
            inventoryleaf.autoSizeColumn(5);

            try (OutputStream archivo = new FileOutputStream(name)) {
                inventorybook.write(archivo);
                JOptionPane.showMessageDialog(rootPane, "Success", "Info", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, something went wrong", "Info", JOptionPane.INFORMATION_MESSAGE);
                ex.getStackTrace();
            }
        }
    }//GEN-LAST:event_GenerateBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetalleVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDetalleVentas dialog = new FrmDetalleVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setBill(String idfact, String supplier, String line, String regdate) {
        IDField.setText(idfact);
        LineField.setText(line);
        SupplierField.setText(supplier);
        DateField.setText(regdate);
        showbilldetails(Integer.parseInt(idfact));
    }

    private void showbilldetails(int idfact) {
        myModel = (DefaultTableModel) tblSales.getModel();
        LBillsDetails fun = new LBillsDetails();
        DBillsDetails dts = new DBillsDetails();
        dts.setBillsID(idfact);
        myModel = fun.showBillDetails(dts);
        tblSales.setModel(myModel);
        addTotal();
    }

    public void addTotal() {
        DecimalFormat ft = new DecimalFormat("####.00");
        double totalp = 0, total = 0;
        for (int i = 0; i < tblSales.getRowCount(); i++) {
            totalp = Double.parseDouble(tblSales.getValueAt(i, 5).toString());
            total += totalp;
            TotalField.setText(ft.format(total));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateField;
    private javax.swing.JButton GenerateBTN1;
    private javax.swing.JTextField IDField;
    private static javax.swing.JTextField LineField;
    private static javax.swing.JTextField SupplierField;
    private javax.swing.JTextField TotalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables

}
