/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.DStorage;
import Logic.LStorage;
import java.awt.Image;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;

/**
 *
 * @author FeedzOne
 */
public class FrmInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInventario
     */
    public FrmInventario() {
        initComponents();
        showSearch("");
        //BUSCAR
        ImageIcon ImgSearch = new ImageIcon(getClass().getResource("/Images/SEARCH.png"));
        Icon SearchIcon = new ImageIcon(ImgSearch.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SearchBTN.setIcon(SearchIcon);
    }

    public void showSearch(String id) {
        DefaultTableModel myModel;
        LStorage fn = new LStorage();
        DStorage dts = new DStorage();
        dts.setStorageID(id);
        myModel = fn.showInventory(dts);
        tblInventory.setModel(myModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchBTN = new javax.swing.JButton();
        GenerateBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();

        setBackground(new java.awt.Color(24, 24, 27));
        setClosable(true);
        setIconifiable(true);
        setTitle("INVENTORY");

        jPanel1.setBackground(new java.awt.Color(31, 31, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));

        SearchField.setBackground(new java.awt.Color(80, 80, 80));
        SearchField.setForeground(new java.awt.Color(238, 238, 238));

        SearchBTN.setBackground(new java.awt.Color(24, 24, 27));
        SearchBTN.setForeground(new java.awt.Color(238, 238, 238));
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        GenerateBTN.setBackground(new java.awt.Color(24, 24, 27));
        GenerateBTN.setForeground(new java.awt.Color(238, 238, 238));
        GenerateBTN.setText("Generate Report");
        GenerateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBTNActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("CODE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SearchBTN)
                                .addGap(65, 65, 65)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(GenerateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchBTN)
                .addGap(73, 73, 73)
                .addComponent(GenerateBTN)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(31, 31, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblInventory.setBackground(new java.awt.Color(80, 80, 80));
        tblInventory.setForeground(new java.awt.Color(238, 238, 238));
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "DESCRIPTION", "QUANTITY", "UNIT", "PRICE", "TOTAL", "LINE"
            }
        ));
        jScrollPane1.setViewportView(tblInventory);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        showSearch(SearchField.getText());
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void GenerateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBTNActionPerformed
        // TODO add your handling code here:
        JFileChooser selection = new JFileChooser();
        int op = selection.showSaveDialog(null);
        if (op == JFileChooser.APPROVE_OPTION) {
            String route = selection.getSelectedFile().getAbsolutePath();
            String name = route + ".xlsx";
            String reportname = "Inventory";
            XSSFWorkbook inventorybook = new XSSFWorkbook();
            XSSFSheet inventoryleaf = inventorybook.createSheet(reportname);

            String[] titles = new String[]{"CODE", "DESCRIPTION", "QUANTITY", "UNIT", "PRICE", "TOTAL", "LINE"};

            Font titlesfont = inventorybook.createFont();
            titlesfont.setBold(true);

            XSSFRow title = inventoryleaf.createRow(0);
            for (int i = 0; i < titles.length; i++) {
                XSSFCell cell = title.createCell(i);
                cell.setCellValue(titles[i]);
            }
            int inventoryRow = 1;
            for (int i = 0; i < tblInventory.getRowCount(); i++) {
                XSSFRow content = inventoryleaf.createRow(inventoryRow);
                inventoryRow++;
                for(int j = 0; j < tblInventory.getColumnCount(); j++){
                    XSSFCell cell = content.createCell(j);
                    cell.setCellValue(tblInventory.getValueAt(i, j).toString());
                }          
            }
            inventoryleaf.autoSizeColumn(0);
            inventoryleaf.autoSizeColumn(1);
            inventoryleaf.autoSizeColumn(2);
            inventoryleaf.autoSizeColumn(3);
            inventoryleaf.autoSizeColumn(4);
            inventoryleaf.autoSizeColumn(5);
            inventoryleaf.autoSizeColumn(6);
            try(OutputStream archivo = new FileOutputStream(name)){
                inventorybook.write(archivo);
                JOptionPane.showMessageDialog(rootPane, "Success", "Info", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex){
                JOptionPane.showMessageDialog(rootPane, "Uh oh, something went wrong", "Info", JOptionPane.INFORMATION_MESSAGE);
                ex.getStackTrace();
            }
        }
    }//GEN-LAST:event_GenerateBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventory;
    // End of variables declaration//GEN-END:variables
}
