/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.DLines;
import Logic.LLines;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/** 
 *
 * @author FeedzOne
 */
public class FrmLineas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLineas
     */
    public FrmLineas() {
        initComponents();
        cleanfield();
        enablebtn(false);
        IDField.setEnabled(false);
        showSearch("");
        
        //NUEVO
        ImageIcon ImgNew = new ImageIcon(getClass().getResource("/Images/NEW.png"));
        Icon NewIcon = new ImageIcon(ImgNew.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        NewBTN.setIcon(NewIcon);
        
        //EDITAR
        ImageIcon ImgEdit = new ImageIcon(getClass().getResource("/Images/EDIT.png"));
        Icon EditIcon = new ImageIcon(ImgEdit.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        EditBTN.setIcon(EditIcon);
        
        //GUARDAR
        ImageIcon ImgSave = new ImageIcon(getClass().getResource("/Images/SAVE.png"));
        Icon SaveIcon = new ImageIcon(ImgSave.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SaveBTN.setIcon(SaveIcon);
        
        //CANCELAR
        ImageIcon ImgCancel = new ImageIcon(getClass().getResource("/Images/CANCEL.png"));
        Icon CancelIcon = new ImageIcon(ImgCancel.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        CancelBTN.setIcon(CancelIcon);
        
        //BUSCAR
        ImageIcon ImgSearch = new ImageIcon(getClass().getResource("/Images/SEARCH.png"));
        Icon SearchIcon = new ImageIcon(ImgSearch.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SearchBTN.setIcon(SearchIcon);
        
        //ELIMINAR
        ImageIcon ImgDelete = new ImageIcon(getClass().getResource("/Images/DELETE.png"));
        Icon DeleteIcon = new ImageIcon(ImgDelete.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        DeleteBTN.setIcon(DeleteIcon);
    }

    public void cleanfield(){
        IDField.setText("");
        LineField.setText("");
    }
    
    public void enablebtn(boolean b){
        LineField.setEnabled(b);
        
        NewBTN.setEnabled(!b);
        EditBTN.setEnabled(!b);
        SaveBTN.setEnabled(b);
        CancelBTN.setEnabled(b);  
    }
    
    public void showSearch(String line){
        DefaultTableModel myModel;
        LLines fn = new LLines();
        DLines dts = new DLines();
        dts.setLine(line);
        myModel = fn.showLines(dts);
        tblLines.setModel(myModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLines = new javax.swing.JTable();
        SearchBTN = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        LineField = new javax.swing.JTextField();
        NewBTN = new javax.swing.JButton();
        EditBTN = new javax.swing.JButton();
        SaveBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(24, 24, 27));
        setClosable(true);
        setForeground(java.awt.Color.darkGray);
        setIconifiable(true);
        setTitle("LINES");

        jPanel1.setBackground(new java.awt.Color(31, 31, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N

        tblLines.setBackground(new java.awt.Color(80, 80, 80));
        tblLines.setForeground(new java.awt.Color(238, 238, 238));
        tblLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLinesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLines);

        SearchBTN.setBackground(new java.awt.Color(24, 24, 27));
        SearchBTN.setForeground(new java.awt.Color(238, 238, 238));
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        SearchField.setBackground(new java.awt.Color(80, 80, 80));
        SearchField.setForeground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(31, 31, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("ID:");

        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Linea:");

        IDField.setBackground(new java.awt.Color(50, 50, 50));
        IDField.setForeground(new java.awt.Color(238, 238, 238));

        LineField.setBackground(new java.awt.Color(80, 80, 80));
        LineField.setForeground(new java.awt.Color(238, 238, 238));

        NewBTN.setBackground(new java.awt.Color(24, 24, 27));
        NewBTN.setForeground(new java.awt.Color(238, 238, 238));
        NewBTN.setText("New");
        NewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBTNActionPerformed(evt);
            }
        });

        EditBTN.setBackground(new java.awt.Color(24, 24, 27));
        EditBTN.setForeground(new java.awt.Color(238, 238, 238));
        EditBTN.setText("Edit");
        EditBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTNActionPerformed(evt);
            }
        });

        SaveBTN.setBackground(new java.awt.Color(24, 24, 27));
        SaveBTN.setForeground(new java.awt.Color(238, 238, 238));
        SaveBTN.setText("Save");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });

        CancelBTN.setBackground(new java.awt.Color(24, 24, 27));
        CancelBTN.setForeground(new java.awt.Color(238, 238, 238));
        CancelBTN.setText("Cancel");
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setBackground(new java.awt.Color(24, 24, 27));
        DeleteBTN.setForeground(new java.awt.Color(238, 238, 238));
        DeleteBTN.setText("Delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LineField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBTNActionPerformed
        // TODO add your handling code here:
        cleanfield();
        enablebtn(true);
        showSearch("");
    }//GEN-LAST:event_NewBTNActionPerformed

    private void EditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTNActionPerformed
        // TODO add your handling code here:
        enablebtn(true);
        showSearch("");
    }//GEN-LAST:event_EditBTNActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        // TODO add your handling code here:
        
        //LINE FIELD
        if(LineField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Line is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            LineField.requestFocusInWindow();
            return;
        }

         String msg = null;
        if(IDField.getText().equals("")){
            LLines fn = new LLines();
            DLines dts = new DLines();
            
            dts.setLine(LineField.getText());
            msg = fn.insertLines(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Successfully Registered", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            LLines fn = new LLines();
            DLines dts = new DLines();

            dts.setID(Integer.parseInt(IDField.getText()));
            dts.setLine(LineField.getText());
            msg = fn.editLines(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Successfully Updated", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }
        cleanfield();
        enablebtn(false);
        showSearch("");
    }//GEN-LAST:event_SaveBTNActionPerformed

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        // TODO add your handling code here:
        cleanfield();
        enablebtn(false);
        showSearch("");
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        // TODO add your handling code here:
        if(!IDField.getText().equals("")){
            LLines fn = new LLines();
            DLines dts = new DLines();
            dts.setID(Integer.parseInt(IDField.getText()));
            String msg = fn.deleteLines(dts);
            if(msg.equals("si")){
                JOptionPane.showMessageDialog(rootPane, "Successfully Updated", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.ERROR_MESSAGE);  
            }  
        }else{
                JOptionPane.showMessageDialog(rootPane, "Select a user to delete", "Info", JOptionPane.ERROR_MESSAGE); 
    }
        cleanfield();
        enablebtn(false);
        showSearch("");
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        showSearch(SearchField.getText());
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void tblLinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLinesMouseClicked
        // TODO add your handling code here:
        int fila = tblLines.getSelectedRow();
        IDField.setText(tblLines.getValueAt(fila, 0).toString());
        LineField.setText(tblLines.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tblLinesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBTN;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton EditBTN;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField LineField;
    private javax.swing.JButton NewBTN;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLines;
    // End of variables declaration//GEN-END:variables
}
