/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.DSuppliers;
import Logic.LSuppliers;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FeedzOne
 */
public class FrmProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProveedores
     */
    public FrmProveedores() {
        initComponents();
        cleanfield();
        enablebtn(false);
        IDField.setEnabled(false);
        showSearch("");
        
        
        //NUEVO
        ImageIcon ImgNew = new ImageIcon(getClass().getResource("/Images/NEW.png"));
        Icon NewIcon = new ImageIcon(ImgNew.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        NewBTN.setIcon(NewIcon);
        
        //EDITAR
        ImageIcon ImgEdit = new ImageIcon(getClass().getResource("/Images/EDIT.png"));
        Icon EditIcon = new ImageIcon(ImgEdit.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        EditBTN.setIcon(EditIcon);
        
        //GUARDAR
        ImageIcon ImgSave = new ImageIcon(getClass().getResource("/Images/SAVE.png"));
        Icon SaveIcon = new ImageIcon(ImgSave.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SaveBTN.setIcon(SaveIcon);
        
        //CANCELAR
        ImageIcon ImgCancel = new ImageIcon(getClass().getResource("/Images/CANCEL.png"));
        Icon CancelIcon = new ImageIcon(ImgCancel.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        CancelBTN.setIcon(CancelIcon);
        
        //BUSCAR
        ImageIcon ImgSearch = new ImageIcon(getClass().getResource("/Images/SEARCH.png"));
        Icon SearchIcon = new ImageIcon(ImgSearch.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SearchBTN.setIcon(SearchIcon);
        
        //ELIMINAR
        ImageIcon ImgDelete = new ImageIcon(getClass().getResource("/Images/DELETE.png"));
        Icon DeleteIcon = new ImageIcon(ImgDelete.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        DeleteBTN.setIcon(DeleteIcon);
    }

    public void cleanfield(){
        IDField.setText("");
        SupplierField.setText("");
        PhoneField.setText("");
        AddressField.setText("");
    }
    
    public void enablebtn(boolean b){
        SupplierField.setEnabled(b);
        PhoneField.setEnabled(b);
        AddressField.setEnabled(b);
        
        NewBTN.setEnabled(!b);
        EditBTN.setEnabled(!b);
        SaveBTN.setEnabled(b);
        CancelBTN.setEnabled(b);  
        //DeleteBTN.setEnabled(b);
    }
    
    public void showSearch(String user){
        DefaultTableModel myModel;
        LSuppliers fn = new LSuppliers();
        DSuppliers dts = new DSuppliers();
        dts.setName(user);
        //dts.setName(SupplierField.getText());
        myModel = fn.showSuppliers(dts);
        tblSuppliers.setModel(myModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        SupplierField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        NewBTN = new javax.swing.JButton();
        EditBTN = new javax.swing.JButton();
        SaveBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        SearchBTN = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        DeleteBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(24, 24, 27));
        setClosable(true);
        setForeground(java.awt.Color.darkGray);
        setIconifiable(true);
        setTitle("SUPPLIERS");

        jPanel1.setBackground(new java.awt.Color(31, 31, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));

        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("ID:");

        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Supplier:");

        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Phone:");

        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Address:");

        IDField.setBackground(new java.awt.Color(50, 50, 50));
        IDField.setForeground(new java.awt.Color(238, 238, 238));

        SupplierField.setBackground(new java.awt.Color(80, 80, 80));
        SupplierField.setForeground(new java.awt.Color(238, 238, 238));

        PhoneField.setBackground(new java.awt.Color(80, 80, 80));
        PhoneField.setForeground(new java.awt.Color(238, 238, 238));

        AddressField.setBackground(new java.awt.Color(80, 80, 80));
        AddressField.setForeground(new java.awt.Color(238, 238, 238));

        NewBTN.setBackground(new java.awt.Color(24, 24, 27));
        NewBTN.setForeground(new java.awt.Color(238, 238, 238));
        NewBTN.setText("New");
        NewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBTNActionPerformed(evt);
            }
        });

        EditBTN.setBackground(new java.awt.Color(24, 24, 27));
        EditBTN.setForeground(new java.awt.Color(238, 238, 238));
        EditBTN.setText("Edit");
        EditBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTNActionPerformed(evt);
            }
        });

        SaveBTN.setBackground(new java.awt.Color(24, 24, 27));
        SaveBTN.setForeground(new java.awt.Color(238, 238, 238));
        SaveBTN.setText("Save");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });

        CancelBTN.setBackground(new java.awt.Color(24, 24, 27));
        CancelBTN.setForeground(new java.awt.Color(238, 238, 238));
        CancelBTN.setText("Cancel");
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneField)
                    .addComponent(SupplierField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddressField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupplierField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );

        jPanel2.setBackground(new java.awt.Color(31, 31, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(238, 238, 238));

        tblSuppliers.setBackground(new java.awt.Color(80, 80, 80));
        tblSuppliers.setForeground(new java.awt.Color(238, 238, 238));
        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        SearchBTN.setBackground(new java.awt.Color(24, 24, 27));
        SearchBTN.setForeground(new java.awt.Color(238, 238, 238));
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        SearchField.setBackground(new java.awt.Color(80, 80, 80));
        SearchField.setForeground(new java.awt.Color(238, 238, 238));
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        DeleteBTN.setBackground(new java.awt.Color(24, 24, 27));
        DeleteBTN.setForeground(new java.awt.Color(238, 238, 238));
        DeleteBTN.setText("Delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBTNActionPerformed
        // TODO add your handling code here:
        cleanfield();
        enablebtn(true);
        showSearch("");
    }//GEN-LAST:event_NewBTNActionPerformed

    private void EditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTNActionPerformed
        // TODO add your handling code here:
        enablebtn(true);
        showSearch("");
    }//GEN-LAST:event_EditBTNActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        // TODO add your handling code here:
        
        //NOMBRE VACIO
        if(SupplierField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Name is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            SupplierField.requestFocusInWindow();
            return;
        }
        
        //TELEFONO VACIO
        if(PhoneField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Phone is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            PhoneField.requestFocusInWindow();
            return;
        }
        
        //DIRECCION VACIA
        if(AddressField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Address is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            AddressField.requestFocusInWindow();
            return;
        }   
        
        String msg = null;
        if(IDField.getText().equals("")){
            DSuppliers dts = new DSuppliers();
            LSuppliers fun = new LSuppliers();

            dts.setName(SupplierField.getText());
            dts.setPhone(PhoneField.getText());
            dts.setAddress(AddressField.getText());
            
            msg = fun.insertSuppliers(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Successfully Registered", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            DSuppliers dts = new DSuppliers();
            LSuppliers fun = new LSuppliers();
            
            dts.setID(Integer.parseInt(IDField.getText()));
            dts.setName(SupplierField.getText());
            dts.setPhone(PhoneField.getText());
            dts.setAddress(AddressField.getText());
            
            msg = fun.editSuppliers(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Successfully Updated", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }
        cleanfield();
        enablebtn(false);
        showSearch("");
    }//GEN-LAST:event_SaveBTNActionPerformed

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        // TODO add your handling code here:
        cleanfield();
        enablebtn(false);
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        // TODO add your handling code here:
        if(!IDField.getText().equals("")){
            DSuppliers dts = new DSuppliers();
            LSuppliers fun = new LSuppliers();
            dts.setID(Integer.parseInt(IDField.getText()));
            String msg = fun.deleteSuppliers(dts);
            if(msg.equals("si")){
                JOptionPane.showMessageDialog(rootPane, "Successfully Updated", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.ERROR_MESSAGE);  
            }  
        }else{
                JOptionPane.showMessageDialog(rootPane, "Select a Supplier to delete", "Info", JOptionPane.ERROR_MESSAGE); 
    }
        cleanfield();
        enablebtn(false);
        showSearch("");
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        showSearch(SearchField.getText());
        
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void tblSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseClicked
        // TODO add your handling code here:
        int fila = tblSuppliers.getSelectedRow();
        IDField.setText(tblSuppliers.getValueAt(fila, 0).toString());
        SupplierField.setText(tblSuppliers.getValueAt(fila, 1).toString());
        PhoneField.setText(tblSuppliers.getValueAt(fila, 2).toString());
        AddressField.setText(tblSuppliers.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tblSuppliersMouseClicked

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton EditBTN;
    private javax.swing.JTextField IDField;
    private javax.swing.JButton NewBTN;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField SupplierField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSuppliers;
    // End of variables declaration//GEN-END:variables
}
