package Presentation;

import Data.DUsers;
import Logic.LUsers;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FeedzOne
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        
        initComponents();
        IDField.setEnabled(false);
        cleanfield();
        enablebtn(true);
        showSearch("");
        
        
        //NUEVO
        ImageIcon ImgNew = new ImageIcon(getClass().getResource("/Images/NEW.png"));
        Icon NewIcon = new ImageIcon(ImgNew.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        NewBTN.setIcon(NewIcon);
        
        //EDITAR
        ImageIcon ImgEdit = new ImageIcon(getClass().getResource("/Images/EDIT.png"));
        Icon EditIcon = new ImageIcon(ImgEdit.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        EditBTN.setIcon(EditIcon);
        
        //GUARDAR
        ImageIcon ImgSave = new ImageIcon(getClass().getResource("/Images/SAVE.png"));
        Icon SaveIcon = new ImageIcon(ImgSave.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SaveBTN.setIcon(SaveIcon);
        
        //CANCELAR
        ImageIcon ImgCancel = new ImageIcon(getClass().getResource("/Images/CANCEL.png"));
        Icon CancelIcon = new ImageIcon(ImgCancel.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        CancelBTN.setIcon(CancelIcon);
        
        //BUSCAR
        ImageIcon ImgSearch = new ImageIcon(getClass().getResource("/Images/SEARCH.png"));
        Icon SearchIcon = new ImageIcon(ImgSearch.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SearchBTN.setIcon(SearchIcon);
        
        //ELIMINAR
        ImageIcon ImgDelete = new ImageIcon(getClass().getResource("/Images/DELETE.png"));
        Icon DeleteIcon = new ImageIcon(ImgDelete.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        DeleteBTN.setIcon(DeleteIcon);
    }

    public void cleanfield(){
        IDField.setText("");
        NameField.setText("");
        UserField.setText("");
        KeyField.setText("");
        ConfirmKeyField.setText("");
        cmbProfile.setSelectedIndex(0); 
    }
    
    public void enablebtn(boolean b){
        //IDField.setEnabled(b);
        NameField.setEnabled(!b);
        UserField.setEnabled(!b);
        KeyField.setEnabled(!b);
        ConfirmKeyField.setEnabled(!b);
        cmbProfile.setEnabled(!b);
        
        NewBTN.setEnabled(b);
        SaveBTN.setEnabled(!b);
        EditBTN.setEnabled(b);
        CancelBTN.setEnabled(!b);  
    }
    
    public void showSearch(String user){
        DefaultTableModel myModel;
        LUsers fn = new LUsers();
        DUsers dts = new DUsers();
        dts.setUser(user);
        myModel = fn.showUsers(dts);
        tblUsers.setModel(myModel);
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        UserField = new javax.swing.JTextField();
        KeyField = new javax.swing.JPasswordField();
        ConfirmKeyField = new javax.swing.JPasswordField();
        cmbProfile = new javax.swing.JComboBox<>();
        NewBTN = new javax.swing.JButton();
        EditBTN = new javax.swing.JButton();
        SaveBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SearchBTN = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        DeleteBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(24, 24, 27));
        setClosable(true);
        setForeground(java.awt.Color.darkGray);
        setIconifiable(true);
        setTitle("Users");

        jPanel1.setBackground(new java.awt.Color(31, 31, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(238, 238, 238));

        jLabel1.setBackground(new java.awt.Color(24, 24, 27));
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("ID:");

        jLabel2.setBackground(new java.awt.Color(24, 24, 27));
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Name:");

        jLabel3.setBackground(new java.awt.Color(24, 24, 27));
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("User:");

        jLabel4.setBackground(new java.awt.Color(24, 24, 27));
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Key:");

        jLabel5.setBackground(new java.awt.Color(24, 24, 27));
        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("Confirm Key:");

        jLabel6.setBackground(new java.awt.Color(24, 24, 27));
        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("Profile");

        IDField.setBackground(new java.awt.Color(50, 50, 50));
        IDField.setForeground(new java.awt.Color(238, 238, 238));
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        NameField.setBackground(new java.awt.Color(80, 80, 80));
        NameField.setForeground(new java.awt.Color(238, 238, 238));

        UserField.setBackground(new java.awt.Color(80, 80, 80));
        UserField.setForeground(new java.awt.Color(238, 238, 238));

        KeyField.setBackground(new java.awt.Color(80, 80, 80));
        KeyField.setForeground(new java.awt.Color(238, 238, 238));

        ConfirmKeyField.setBackground(new java.awt.Color(80, 80, 80));
        ConfirmKeyField.setForeground(new java.awt.Color(238, 238, 238));

        cmbProfile.setBackground(new java.awt.Color(80, 80, 80));
        cmbProfile.setForeground(new java.awt.Color(238, 238, 238));
        cmbProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Profile", "Administrator", "Employee" }));
        cmbProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProfileActionPerformed(evt);
            }
        });

        NewBTN.setBackground(new java.awt.Color(24, 24, 27));
        NewBTN.setForeground(new java.awt.Color(238, 238, 238));
        NewBTN.setText("NEW");
        NewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBTNActionPerformed(evt);
            }
        });

        EditBTN.setBackground(new java.awt.Color(24, 24, 27));
        EditBTN.setForeground(new java.awt.Color(238, 238, 238));
        EditBTN.setText("EDIT");
        EditBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBTNActionPerformed(evt);
            }
        });

        SaveBTN.setBackground(new java.awt.Color(24, 24, 27));
        SaveBTN.setForeground(new java.awt.Color(238, 238, 238));
        SaveBTN.setText("SAVE");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });

        CancelBTN.setBackground(new java.awt.Color(24, 24, 27));
        CancelBTN.setForeground(new java.awt.Color(238, 238, 238));
        CancelBTN.setText("CANCEL");
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameField)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserField)
                            .addComponent(KeyField)
                            .addComponent(ConfirmKeyField)
                            .addComponent(cmbProfile, 0, 171, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SaveBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addGap(70, 70, 70)
                                .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(KeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ConfirmKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jPanel2.setBackground(new java.awt.Color(31, 31, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(238, 238, 238))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(24, 24, 27));

        SearchBTN.setBackground(new java.awt.Color(24, 24, 27));
        SearchBTN.setForeground(new java.awt.Color(238, 238, 238));
        SearchBTN.setText("SEARCH");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        SearchField.setBackground(new java.awt.Color(80, 80, 80));
        SearchField.setForeground(new java.awt.Color(238, 238, 238));
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        tblUsers.setBackground(new java.awt.Color(80, 80, 80));
        tblUsers.setForeground(new java.awt.Color(238, 238, 238));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsers.setSelectionBackground(new java.awt.Color(24, 24, 27));
        tblUsers.setSelectionForeground(new java.awt.Color(238, 238, 238));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        DeleteBTN.setBackground(new java.awt.Color(24, 24, 27));
        DeleteBTN.setForeground(new java.awt.Color(238, 238, 238));
        DeleteBTN.setText("DELETE");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBTN)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBTN)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    //NUEVO
    private void NewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBTNActionPerformed
        // TODO add your handling code here:
        cleanfield();
        enablebtn(false);
    }//GEN-LAST:event_NewBTNActionPerformed
    
    //EDITAR 
    private void EditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBTNActionPerformed
        // TODO add your handling code here:
        enablebtn(false);
    }//GEN-LAST:event_EditBTNActionPerformed
    
    //CANCELAR
    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        // TODO add your handling code here:
        cleanfield();
        enablebtn(true);
    }//GEN-LAST:event_CancelBTNActionPerformed
    
    //GUARDAR
    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        // TODO add your handling code here:
        
        //NOMBRE VACIO
        if(NameField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Name is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            NameField.requestFocusInWindow();
            return;
        }
        
        //USUARIO VACIO
        if(UserField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "User is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            UserField.requestFocusInWindow();
            return;
        }
        
        //PASSWORD VACIA
        String keyt = new String(KeyField.getPassword());
        if(keyt.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Password is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            KeyField.requestFocusInWindow();
            return;
        }
        
        //CONFIRMAR PASSWORD
        String keyt2 = new String(ConfirmKeyField.getPassword());
        if(keyt2.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Password confirmation is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            ConfirmKeyField.requestFocusInWindow();
            return;
        }
        
        //PASSWORD NO COINCIDEN
        if(!keyt.equals(keyt2)){
            JOptionPane.showMessageDialog(rootPane, "Passwords dont be equals", "Validation", JOptionPane.WARNING_MESSAGE); 
            KeyField.requestFocusInWindow();
            KeyField.setText("");
            ConfirmKeyField.setText("");
            return;
        }
        
        //PERFIL VACIO
        if(cmbProfile.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Profile is required", "Validation", JOptionPane.WARNING_MESSAGE); 
            cmbProfile.requestFocusInWindow();
            return;
        }
        
        
        String msg = null;
        if(IDField.getText().equals("")){
            DUsers dts = new DUsers();
            LUsers fun = new LUsers();
            
            String key = new String(KeyField.getPassword());
            String profile = String.valueOf(cmbProfile.getSelectedItem());
            dts.setName(NameField.getText());
            dts.setUser(UserField.getText());
            dts.setKey(key);
            dts.setProfile(profile);
            msg = fun.insertUsers(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Successfully Registered", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            DUsers dts = new DUsers();
            LUsers fun = new LUsers();
            
            String key = new String(KeyField.getPassword());
            String profile = String.valueOf(cmbProfile.getSelectedItem());
            dts.setIDUsers(Integer.parseInt(IDField.getText()));
            dts.setName(NameField.getText());
            dts.setUser(UserField.getText());
            dts.setKey(key);
            dts.setProfile(profile);
            msg = fun.editUsers(dts);
            if(msg == "si"){
               JOptionPane.showMessageDialog(rootPane, "Successfully Updated", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
        }
        cleanfield();
        enablebtn(true);
        showSearch("");
    }//GEN-LAST:event_SaveBTNActionPerformed

    //ELIMINAR
    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
        // TODO add your handling code here:
        
        if(!IDField.getText().equals("")){
            DUsers dts = new DUsers();
            LUsers fn = new LUsers();
            dts.setIDUsers(Integer.parseInt(IDField.getText()));
            String msg = fn.deleteUsers(dts);
            if(msg.equals("si")){
                JOptionPane.showMessageDialog(rootPane, "Successfully Updated", "Info", JOptionPane.INFORMATION_MESSAGE); 
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.ERROR_MESSAGE);  
            }  
        }else{
                JOptionPane.showMessageDialog(rootPane, "Select a user to delete", "Info", JOptionPane.ERROR_MESSAGE); 
    }
        
        cleanfield();
        enablebtn(true);
        showSearch("");
    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        int fila = tblUsers.getSelectedRow();
        IDField.setText(tblUsers.getValueAt(fila, 0).toString());
        NameField.setText(tblUsers.getValueAt(fila, 1).toString());
        UserField.setText(tblUsers.getValueAt(fila, 2).toString());
        KeyField.setText(tblUsers.getValueAt(fila, 3).toString());
        ConfirmKeyField.setText(tblUsers.getValueAt(fila, 3).toString());
        cmbProfile.setSelectedItem(tblUsers.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tblUsersMouseClicked

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        showSearch(SearchField.getText());
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void cmbProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBTN;
    private javax.swing.JPasswordField ConfirmKeyField;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton EditBTN;
    private javax.swing.JTextField IDField;
    private javax.swing.JPasswordField KeyField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton NewBTN;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField UserField;
    private javax.swing.JComboBox<String> cmbProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
