/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.DBillsDetails;
import Data.DSales;
import Data.DStorage;
import Logic.LBillsDetails;
import Logic.LSales;
import Logic.LStorage;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FeedzOne
 */
public class FrmVentas extends javax.swing.JInternalFrame {

    DefaultTableModel myModel;
    static int LinesID = 0;

    /**
     * Creates new form FrmVentas
     */
    public FrmVentas() {
        initComponents();
        jLabel1.setVisible(false);
        IDField.setVisible(false);
        LineID.setVisible(false);
        SupplierID.setVisible(false);
        IDField.setEnabled(false);
        TotalField.setEditable(false);

        myModel = (DefaultTableModel) tblSales.getModel();

        tblSales.getColumn("CODE").setWidth(15);
        tblSales.getColumn("CODE").setPreferredWidth(15);

        tblSales.getColumn("DESCRIPTION").setWidth(200);
        tblSales.getColumn("DESCRIPTION").setPreferredWidth(200);

        tblSales.getColumn("QUANTITY").setWidth(20);
        tblSales.getColumn("QUANTITY").setPreferredWidth(20);

        tblSales.getColumn("UNIT").setWidth(20);
        tblSales.getColumn("UNIT").setPreferredWidth(20);

        tblSales.getColumn("PRICE/UNIT").setWidth(20);
        tblSales.getColumn("PRICE/UNIT").setPreferredWidth(20);

        tblSales.getColumn("TOTAL").setWidth(20);
        tblSales.getColumn("TOTAL").setPreferredWidth(20);

        LineID.setEnabled(false);
        SupplierID.setEnabled(false);
        //NUEVO
        ImageIcon ImgNew = new ImageIcon(getClass().getResource("/Images/NEW.png"));
        Icon NewIcon = new ImageIcon(ImgNew.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        NewBTN.setIcon(NewIcon);

        //GUARDAR
        ImageIcon ImgSave = new ImageIcon(getClass().getResource("/Images/SAVE.png"));
        Icon SaveIcon = new ImageIcon(ImgSave.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        SaveBTN.setIcon(SaveIcon);

        //CANCELAR
        ImageIcon ImgCancel = new ImageIcon(getClass().getResource("/Images/CANCEL.png"));
        Icon CancelIcon = new ImageIcon(ImgCancel.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
        CancelBTN.setIcon(CancelIcon);
    }

    public static void setSupplier(String id, String supplier) {
        SupplierID.setText(id);
        SupplierField.setText(supplier);
    }

    public static void setLine(String id, String supplier) {
        LinesID = Integer.parseInt(id);
        LineID.setText(id);
        LineField.setText(supplier);
    }

    public void cleanfield() {
        //LinesID = 0;
        EnterField.setText("");
        DateField.setDate(null);
        LineField.setText("");
        SupplierField.setText("");
        IDField.setText("");
        LineID.setText("");
        SupplierID.setText("");
        TotalField.setText("");
        try {
            DefaultTableModel model = (DefaultTableModel) tblSales.getModel();
            int filas = tblSales.getRowCount();
            for (int i = 0; filas > i; i++) {
                model.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error cleaning table...");
        }
    }

    public void enablebtn(boolean b) {
        EnterField.setEnabled(!b);
        DateField.setEnabled(!b);
        LineField.setEnabled(!b);
        SupplierField.setEnabled(!b);
        CancelBTN.setEnabled(!b);
        SaveBTN.setEnabled(!b);
        LineBTN.setEnabled(!b);
        SupplierBTN.setEnabled(!b);
        NewBTN.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DateField = new com.toedter.calendar.JDateChooser();
        SupplierField = new javax.swing.JTextField();
        LineField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        NewBTN = new javax.swing.JButton();
        SaveBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        LineBTN = new javax.swing.JButton();
        SupplierBTN = new javax.swing.JButton();
        LineID = new javax.swing.JTextField();
        SupplierID = new javax.swing.JTextField();
        EnterField = new javax.swing.JTextField();
        TotalField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 24, 27));
        setClosable(true);
        setIconifiable(true);
        setTitle("SALES");

        jPanel1.setBackground(new java.awt.Color(31, 31, 35));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setBackground(new java.awt.Color(24, 24, 27));
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("ID:");

        jLabel2.setBackground(new java.awt.Color(24, 24, 27));
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Line:");

        jLabel3.setBackground(new java.awt.Color(24, 24, 27));
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Supplier:");

        jLabel4.setBackground(new java.awt.Color(24, 24, 27));
        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("Date:");

        DateField.setBackground(new java.awt.Color(80, 80, 80));
        DateField.setForeground(new java.awt.Color(238, 238, 238));

        SupplierField.setBackground(new java.awt.Color(80, 80, 80));
        SupplierField.setForeground(new java.awt.Color(238, 238, 238));

        LineField.setBackground(new java.awt.Color(80, 80, 80));
        LineField.setForeground(new java.awt.Color(238, 238, 238));

        IDField.setBackground(new java.awt.Color(50, 50, 50));
        IDField.setForeground(new java.awt.Color(238, 238, 238));

        tblSales.setBackground(new java.awt.Color(80, 80, 80));
        tblSales.setForeground(new java.awt.Color(238, 238, 238));
        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "DESCRIPTION", "QUANTITY", "UNIT", "PRICE/UNIT", "TOTAL"
            }
        ));
        tblSales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSalesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblSales);

        NewBTN.setBackground(new java.awt.Color(24, 24, 27));
        NewBTN.setForeground(new java.awt.Color(238, 238, 238));
        NewBTN.setText("New");
        NewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBTNActionPerformed(evt);
            }
        });

        SaveBTN.setBackground(new java.awt.Color(24, 24, 27));
        SaveBTN.setForeground(new java.awt.Color(238, 238, 238));
        SaveBTN.setText("Save");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });

        CancelBTN.setBackground(new java.awt.Color(24, 24, 27));
        CancelBTN.setForeground(new java.awt.Color(238, 238, 238));
        CancelBTN.setText("Cancel");
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });

        LineBTN.setBackground(new java.awt.Color(24, 24, 27));
        LineBTN.setForeground(new java.awt.Color(238, 238, 238));
        LineBTN.setText("...");
        LineBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineBTNActionPerformed(evt);
            }
        });

        SupplierBTN.setBackground(new java.awt.Color(24, 24, 27));
        SupplierBTN.setForeground(new java.awt.Color(238, 238, 238));
        SupplierBTN.setText("...");
        SupplierBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierBTNActionPerformed(evt);
            }
        });

        LineID.setBackground(new java.awt.Color(80, 80, 80));
        LineID.setForeground(new java.awt.Color(238, 238, 238));

        SupplierID.setBackground(new java.awt.Color(80, 80, 80));
        SupplierID.setForeground(new java.awt.Color(238, 238, 238));

        EnterField.setBackground(new java.awt.Color(80, 80, 80));
        EnterField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EnterField.setForeground(new java.awt.Color(238, 238, 238));
        EnterField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterFieldKeyPressed(evt);
            }
        });

        TotalField.setBackground(new java.awt.Color(80, 80, 80));
        TotalField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TotalField.setForeground(new java.awt.Color(238, 238, 238));
        TotalField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("TOTAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(LineField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LineBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SupplierID, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(LineID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LineBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SupplierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4))
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(EnterField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBTNActionPerformed
        /*// TODO add your handling code here:
        int filas = tblSales.getRowCount();
        int contar = 1;
        for(int n = 0; filas > n; n++){
            contar = contar + 1;
        }
        if(contar >= 10){
           myModel.addRow(new Object[]{contar,"","","","",""}); 
        }else{
            myModel.addRow(new Object[]{"0"+contar,"","","","",""}); 
        }*/
        enablebtn(false);

    }//GEN-LAST:event_NewBTNActionPerformed

    private void LineBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineBTNActionPerformed
        // TODO add your handling code here:
        FrmBuscarLineas mi = new FrmBuscarLineas(new JFrame(), true);
        mi.setLocationRelativeTo(null);
        mi.setVisible(true);
    }//GEN-LAST:event_LineBTNActionPerformed

    private void SupplierBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierBTNActionPerformed
        // TODO add your handling code here:
        FrmBuscarProveedores mi = new FrmBuscarProveedores(new JFrame(), true);
        mi.setLocationRelativeTo(null);
        mi.setVisible(true);
    }//GEN-LAST:event_SupplierBTNActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        // TODO add your handling code here:
        if (LineField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Line is required", "Validation", JOptionPane.WARNING_MESSAGE);
            LineField.requestFocusInWindow();
            return;
        }

        if (SupplierField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Supplier is required", "Validation", JOptionPane.WARNING_MESSAGE);
            SupplierField.requestFocusInWindow();
            return;
        }
        if (DateField.getDate().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Date is required", "Validation", JOptionPane.WARNING_MESSAGE);
            DateField.requestFocusInWindow();
            return;
        }

        String msg = null, msgfinal = "";

        if (IDField.getText().equals("")) {
            LSales fn = new LSales();
            DSales dts = new DSales();

            dts.setLinesID(Integer.parseInt(LineID.getText()));
            dts.setSupplierID(Integer.parseInt(SupplierID.getText()));

            Calendar cal;
            cal = DateField.getCalendar();
            int aa, mm, dd;
            aa = cal.get(Calendar.YEAR) - 1900;
            mm = cal.get(Calendar.MONTH);
            dd = cal.get(Calendar.DAY_OF_MONTH);

            dts.setEntryDate(new Date(aa, mm, dd));

            //CLEANING FIELDS
            LineField.setText("");
            SupplierField.setText("");
            LineField.setEnabled(false);
            SupplierField.setEnabled(false);

            int idfact = fn.insertSale(dts);
            if (idfact > 0) {
                int filas = tblSales.getRowCount();
                for (int i = 0; i < filas; i++) {
                    String idprod = tblSales.getValueAt(i, 0).toString();
                    String desc = tblSales.getValueAt(i, 1).toString();
                    int qty = Integer.parseInt(tblSales.getValueAt(i, 2).toString());
                    String munit = tblSales.getValueAt(i, 3).toString();
                    double unitprice = Double.parseDouble(tblSales.getValueAt(i, 4).toString());
                    double total = Double.parseDouble(tblSales.getValueAt(i, 4).toString());

                    LBillsDetails fundf = new LBillsDetails();
                    DBillsDetails dtsf = new DBillsDetails();

                    dtsf.setBillsID(idfact);
                    dtsf.setProductID(idprod);
                    dtsf.setQuantity(qty);
                    dtsf.setTotal(total);

                    String msg2 = fundf.RegisterDetailsBills(dtsf);
                    if (msg2.equals("si")) {
                        LStorage funal = new LStorage();
                        DStorage dtsp = new DStorage();

                        dtsp.setStorageID(idprod);
                        dtsp.setDescription(desc);
                        dtsp.setStock(qty);
                        dtsp.setMetricUnit(munit);
                        dtsp.setPrice(unitprice);
                        dtsp.setLinesID(LinesID);

                        msgfinal = funal.insertProducts(dtsp);
                    }
                }
                JOptionPane.showMessageDialog(rootPane, msgfinal, "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Uh oh, an error has occurred", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            enablebtn(true);
            cleanfield();
        }
    }//GEN-LAST:event_SaveBTNActionPerformed

    public boolean isintable(String text) {
        boolean res = false;
        DecimalFormat ft = new DecimalFormat("####.00");
        for (int i = 0; i < tblSales.getRowCount(); i++) {
            String code = tblSales.getValueAt(i, 0).toString();
            if (code.equals(text)) {
                int quantity = Integer.parseInt(tblSales.getValueAt(i, 2).toString());
                double unitprice = Double.parseDouble(tblSales.getValueAt(i, 4).toString());
                int totalqty = quantity + 1;
                tblSales.setValueAt(totalqty, i, 2);

                double totalpar = unitprice * totalqty;
                tblSales.setValueAt(ft.format(totalpar), i, 5);
                res = true;
            }
        }
        addTotal();
        return res;
    }

    public void addTotal() {
        DecimalFormat ft = new DecimalFormat("####.00");
        double totalp = 0, total = 0;
        for (int i = 0; i < tblSales.getRowCount(); i++) {
            totalp = Double.parseDouble(tblSales.getValueAt(i, 5).toString());
            total += totalp;
            TotalField.setText(ft.format(total));
        }
    }


    private void EnterFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean b = isintable(EnterField.getText());
            if (b == false) {
                showProducts(EnterField.getText());
            }
            addTotal();
            EnterField.setText("");
        }
        /*if(key == KeyEvent.VK_ENTER){
            showProducts(Integer.parseInt(EnterField.getText()));
        }*/
    }//GEN-LAST:event_EnterFieldKeyPressed

    private void tblSalesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSalesKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        DecimalFormat ft = new DecimalFormat("####.00");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            for (int i = 0; i < tblSales.getRowCount(); i++) {
                int quantity = Integer.parseInt(tblSales.getValueAt(i, 2).toString());
                double unitprice = Double.parseDouble(tblSales.getValueAt(i, 4).toString());

                double totalpar = quantity * unitprice;
                tblSales.setValueAt(ft.format(totalpar), i, 5);
            }
            addTotal();
        }
    }//GEN-LAST:event_tblSalesKeyPressed

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        // TODO add your handling code here:
        enablebtn(true);
        cleanfield();
    }//GEN-LAST:event_CancelBTNActionPerformed

    public void showProducts(String product) {
        //System.out.println("Dio Enter "+ product);
        LStorage fn = new LStorage();
        DStorage dts = new DStorage();
        DefaultTableModel tblData = (DefaultTableModel) tblSales.getModel();
        dts.setStorageID(product);
        String reg[] = fn.searchshowProducts(dts);
        if (reg[0] != null) {
            tblData.insertRow(0, reg);
            tblSales.setModel(tblData);
        } else {
            reg[0] = EnterField.getText();
            reg[1] = "";
            reg[2] = "1";
            reg[3] = "";
            reg[4] = "0.00";
            reg[5] = "0.00";
            tblData.insertRow(0, reg);
            tblSales.setModel(tblData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBTN;
    private com.toedter.calendar.JDateChooser DateField;
    private javax.swing.JTextField EnterField;
    private javax.swing.JTextField IDField;
    private javax.swing.JButton LineBTN;
    private static javax.swing.JTextField LineField;
    private static javax.swing.JTextField LineID;
    private javax.swing.JButton NewBTN;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JButton SupplierBTN;
    private static javax.swing.JTextField SupplierField;
    private static javax.swing.JTextField SupplierID;
    private javax.swing.JTextField TotalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables

}
